# Generated by Django 4.1.6 on 2023-02-01 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelagentprofile',
            name='name',
            field=models.CharField(default='placeholder', max_length=255),
            preserve_default=False,
        ),
    ]
