# Generated by Django 4.1.6 on 2023-02-01 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_travelagentprofile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelagentprofile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
